apiVersion: v1
kind: Pod
metadata:
  name: maven-web-apppod
  labels:
    app: maven-web-app
    namespace: amns
spec:
  containers:
  - name: maven-web-appcontainer
    image: amiya777/maven-web-app
     ports:
      - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: maven-web-appsvc
  namespace: amns
spec:
  type: NodePort
  selector:
    app: maven-web-app
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001
